#!/usr/bin/env Rscript
# Salmon QC Plots for GSE124439
# Date: April 16, 2026
# Path: /mnt/h/KAUST/tdp43-dysfunction-score/scripts/Rahmas_scripts/validation/GSE124439/02_quantification/salmon_qc_plots.R

cat("==================================================\n")
cat("Salmon QC Visualization - GSE124439\n")
cat("==================================================\n\n")

# Load libraries
suppressPackageStartupMessages({
  library(jsonlite)
  library(ggplot2)
  library(dplyr)
  library(tidyr)
})

# 1. Setup Paths
PROJECT_DIR <- "/mnt/h/KAUST/tdp43-dysfunction-score"
BASE_DIR <- file.path(PROJECT_DIR, "scripts/Rahmas_scripts/validation/GSE124439")
SALMON_DIR <- file.path(BASE_DIR, "results/salmon")
QC_OUT_DIR <- file.path(BASE_DIR, "results/qc/salmon")

# Create output directory
dir.create(QC_OUT_DIR, recursive = TRUE, showWarnings = FALSE)

# 2. Define 18 Samples
samples <- data.frame(
  sample_id = c(paste0("ALS-", 1:9), paste0("Control-", 1:9)),
  condition = c(rep("ALS", 9), rep("Control", 9)),
  stringsAsFactors = FALSE
)

cat("Reading Salmon metadata from:", SALMON_DIR, "\n")

# 3. Extract metadata
metadata_list <- list()

for (i in 1:nrow(samples)) {
  sample <- samples$sample_id[i]
  
  # Path to the meta_info.json generated by your run_salmon.sh
  meta_file <- file.path(SALMON_DIR, sample, "aux_info/meta_info.json")
  
  if (file.exists(meta_file)) {
    meta <- fromJSON(meta_file)
    metadata_list[[sample]] <- list(
      sample = sample,
      condition = samples$condition[i],
      num_processed = meta$num_processed,
      num_mapped = meta$num_mapped,
      mapping_rate = meta$percent_mapped,
      num_targets = meta$num_targets
    )
  } else {
    cat("Warning: Missing metadata for", sample, "\n")
  }
}

qc_data <- bind_rows(metadata_list)
cat("\nQC Summary Data Loaded.\n")

# 4. Generate Plots
cat("\nGenerating plots in:", QC_OUT_DIR, "...\n")

# Plot 1: Mapping Rate
p1 <- ggplot(qc_data, aes(x = sample, y = mapping_rate, fill = condition)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = paste0(round(mapping_rate, 1), "%")), vjust = -0.5, size = 2.5) +
  scale_fill_manual(values = c("ALS" = "#E74C3C", "Control" = "#2ECC71")) +
  labs(title = "Salmon Mapping Rates (GSE124439)", x = "Sample", y = "Mapping Rate (%)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, 100)

ggsave(file.path(QC_OUT_DIR, "mapping_rates.png"), p1, width = 10, height = 6)

# Plot 2: Library Size
p2 <- ggplot(qc_data, aes(x = sample, y = num_processed / 1e6, fill = condition)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("ALS" = "#E74C3C", "Control" = "#2ECC71")) +
  labs(title = "Library Sizes (GSE124439)", x = "Sample", y = "Millions of Reads") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave(file.path(QC_OUT_DIR, "library_sizes.png"), p2, width = 10, height = 6)

# 5. Save CSVs
write.csv(qc_data, file.path(QC_OUT_DIR, "qc_metrics.csv"), row.names = FALSE)

cat("\n✓ QC Visualization Complete!\n")
